### ISSUE TITLE
Greenify

### ISSUE THREAD

**Issue by cocka11** [Magisk-Modules-Repo/submission#1015] opened 2021-09-30 05:22 UTC
Greenify is a free app for Android that helps you to identify power consuming apps and place them into hibernation when you are not using them. Not only does this stop them from eating at your battery, but it also prevents them from slowing down your device.

https://github.com/cocka11/Greenify

**Comment by orges** [comment] 2021-09-30 06:45
duplicate of #994 ?

**Comment by HuskyDG** [comment] 2021-10-02 03:51
Add [submission] 
MagiskBot will add your repository to Magisk-Module-Repositories

**Closed as completed** 2021-12-23 19:38 UTC
